### PR TITLE
fix color and slideshow

### PR DESCRIPTION
**Pull request by lehongson1912**
@sahilatIIT @saugusth

### CODE REVIEW

**Comment by saugusth** [comment]
Good work

**Review by sahil-at-home1 — CHANGES_REQUESTED** [review]
Great work on the carousel. The only thing I'm thinking about is if we should put the search bar or not. I know marketing included it in their demo, but I don't think we will have enough time to implement the logic behind it, so I think we should remove it.

**Comment by saugusth** [comment]
I agree with the no search bar

**Comment by lehongson1912** [comment]
Yeahh im cool with whatever the group decides, so No search bar

**Pull request merged**
